name: Customer Docker Image

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [infra_ready]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.dockerId.outputs.image-version}}

    steps:
      - uses: actions/checkout@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Node setup
        uses: actions/setup-node@v4

      - name: Build docker
        id: dockerId
        run: |
          YEAR=$(date +'%Y')
          MONTH=$(date +'%m')
          BUILD=${{github.run_number}}
          IMAGE_VERSION="${YEAR}.${MONTH}.${BUILD}"
          echo "image-version=${IMAGE_VERSION}" >> $GITHUB_OUTPUT

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t my-react-app .
          docker tag my-react-app:latest ${{vars.ECR_REPO}}:will-mf-${{steps.dockerId.outputs.image-version}}

      - name: Push Docker image
        run: |
          docker push ${{vars.ECR_REPO}}:will-mf-${{steps.dockerId.outputs.image-version}}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}}
      - name: Configure EKS
        run: aws eks update-kubeconfig --region ${{vars.AWS_REGION}} --name inherix-dev
      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/customer.yml
      - name: apply to EKS
        run: kubectl set image deployment/will-mf-app-deployment will-mf-container=${{ vars.ECR_REPO }}:will-mf-${{ needs.build.outputs.image }}
      - name: Verify rollout
        run: |
          kubectl rollout status deployment/will-mf-app-deployment
